# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxmk3ycp89J7h2Kq_NSYYQuYtF94amIO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("sales_data_sample.csv", encoding='latin-1')
print(data.head())

print(data.isnull())

missing_values_per_column = data.isnull().sum()
print(missing_values_per_column)

rows_with_missing_values = data[data.isnull().any(axis=1)]
print(rows_with_missing_values)

data_cleaned_columns = data.dropna(axis=1)
print(data_cleaned_columns)

avg_price_per_product = data.groupby('PRODUCTLINE')['PRICEEACH'].mean()
print(avg_price_per_product)

total_sales_per_category = data.groupby('PRODUCTLINE')['PRICEEACH'].sum()
print(total_sales_per_category)

data['Year'] = data['ORDERDATE'].dt.year
total_sales_per_year = data.groupby('Year')['PRICEEACH'].sum()
print(total_sales_per_year)

data['Month'] = data['ORDERDATE'].dt.month
total_sales_per_month = data.groupby('Month')['PRICEEACH'].sum()
print(total_sales_per_month)

total_sales_per_country = data.groupby('COUNTRY')['SALES'].sum()
print(total_sales_per_country)

plt.figure(figsize=(8, 5))
total_sales_per_country.plot(kind='bar', color='skyblue')
plt.title('Total Penjualan per Negara, 2024')
plt.xlabel('Wilayah')
plt.ylabel('Total Penjualan ')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
total_sales_per_month.plot(kind='line', marker='o', color='green')
plt.title('Total Penjualan per Bulan, 2024')
plt.xlabel('Bulan')
plt.ylabel('Total Penjualan')
plt.xticks(np.arange(1, 13, step=1))
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
total_sales_per_year.plot(kind='bar', color='yellow')
plt.title('Total Penjualan per Tahun')
plt.ylabel('Total Penjualan')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()